version: '3.9'

services:
  app:
    image: ijimiguel/my-json-server:latest
    user: "${UID}:${GID}" # has to have rights to the data folder and tokens_file
    ports:
      - '3000:3000' # external:internal, since CONFIG.PORT defaults to 3000
    environment:
      ALLOWED_ORIGIN: '*'
      RATE_LIMIT_WINDOW_MS: 60000
      RATE_LIMIT_MAX: 100
    volumes:
      - ./data:/app/data # writable local folder for app data
      - ./myApiKeys.json:/app/apiKeys.json:ro # user-provided token file (read-only)
